spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql_demo?autoReconnect=false&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database-platform: mysql
    hibernate:
      ddl-auto: update