server:
  port: 9000
logging:
  level:
    root: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?autoReconnect=false&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      database: MYSQL
      show-sql: false
      properties:
        hibernate:
          type: trace
